" Start with a clean palette
set nocompatible
" Disable modelines for security reasons
set nomodeline
" Allow backspacing over everything when in insert mode
set bs=indent,eol,start
" Enable source code highlighting
syntax on
" Control tab size and reindent size
filetype indent on
set tabstop=8
set softtabstop=8
set shiftwidth=8
" Expand tabs into spaces
set expandtab
" Make code viewing easier
set ruler
set scrolloff=10
" Tweak search settings
set ignorecase
set smartcase
set hlsearch
set nowrapscan
" Help keep us within sane line lengths
match ErrorMsg '\%>80v.\+'
" Special indent sizes, per language (i.e. file extension)
autocmd BufEnter *.bash set tabstop=8 softtabstop=8 shiftwidth=8
autocmd BufEnter *.js set tabstop=2 softtabstop=2 shiftwidth=2
autocmd BufEnter *.json set tabstop=2 softtabstop=2 shiftwidth=2
autocmd BufEnter *.py set tabstop=4 softtabstop=4 shiftwidth=4
autocmd BufEnter *.yml set tabstop=2 softtabstop=2 shiftwidth=2
" Jump to the position in file from last editing session
if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
    \| exe "normal! g'\"" | endif
endif
